#!/usr/bin/env bash

set -euo pipefail

build_repo() {
  if [[ -f "$1/.nojekyll" ]]; then
    publish_dir "$1/" "$2"
  else
    (
      cd "$1"
      mkdir -p _site
      set -x
      docker run --label=jekyll --rm --volume="$PWD:/srv/jekyll" jekyll/builder jekyll build
    )
    publish_dir "$1/_site/" "$2"
  fi
}

publish_dir() {
  mkdir -p "$2"
  rsync --archive --exclude=".*" --verbose -- "$1" "$2"
}

if [[ $# -lt 1 ]]; then
  echo "Usage: build-site DEST" >&2;
  exit 1
fi

while read -r repo; do
  name="$(basename "$repo")"
  case "$name" in
    *.github.io)
      build_repo "$repo" "$1"
    ;;
    *)
      build_repo "$repo" "$1/$name"
    ;;
  esac
done


