#!/bin/bash

set -euo pipefail

if [[ -z "${PAGES_DEPLOY_URL-}" ]]; then
  echo 'Error: must set $PAGES_DEPLOY_URL' >&2
  exit 1
fi

dest_is_root=

while getopts r opt; do
  case "$opt" in
    r) dest_is_root=1
  esac
  shift $(( OPTIND - 1 ))
done

site="$(basename "$1")"

if [ -n "$dest_is_root" ]; then
  dest=""
else
  dest="$site/"
fi

if [ -z "$site" ]; then
  echo "Usage: build-site SITEDIR" >&2;
  exit 1
fi

set -x

if [ -f "$site/.nojekyll" ]; then
  rsync -r "$site/" "$PAGES_DEPLOY_URL/$dest"
else
  (
    cd "$site" &&
    mkdir -p _site &&
    docker run --label=jekyll --volume=$PWD:/srv/jekyll jekyll/builder jekyll build &&
    rsync -r _site/ "$PAGES_DEPLOY_URL/$dest"
  )
fi
