#!/bin/bash

set -euo pipefail

curl -s -u "$(cat ~/.github-creds)" "https://api.github.com/user/repos?type=owner&per_page=100" |
  jq -r '.[] | ([.name, .branches_url, .git_url] | join(" "))' |
  while read -r name branches_url git_url rest; do
    if [[ -f ".$name" || -d "$name" ]]; then
      continue
    fi
    echo "Checking $name"

    list_branches_url=$(printf '%s\n' "$branches_url" | sed -E 's/\{.*\}//')
    if curl -s -u "$(cat ~/.github-creds)" -- "$list_branches_url" |
      jq -r '.[].name' |
      grep -Eq '^(pages|gh-pages)$'; then
      git clone -- "$git_url"
    else
      :> ".$name"
    fi
  done
