#!/bin/bash

set -euo pipefail

dest="${1:-${PAGES_DEPLOY_DEST-}}"
if [[ -z "$dest" ]]; then
  echo 'Usage: publish DEST'
  echo
  echo 'See the rsync(1) man page for valid DESTinations.'
  exit 1
fi

set -x

./get-repos ./repos | ./build-site ./site

rsync -r site/ "$dest"
