#!/bin/bash

set -euo pipefail

dest="${1:-${PAGES_DEPLOY_DEST-}}"
if [[ -z "$dest" ]]; then
  echo 'Usage: publish DEST'
  echo
  echo 'See the rsync(1) man page for valid DESTinations.'
  exit 1
fi

script_dir="$(dirname "$0")"

set -x

(
  cd "$script_dir"
  ./get-repos.docker ./repos | ./build-site ./site
  rsync -r site/ "$dest"
)
