#!/bin/bash

set -euo pipefail

switch_to_branch() {
  (
    cd "$d"
    git fetch
    if [[ $(git rev-parse HEAD) != $(git rev-parse "origin/$1") ]]; then
      git checkout "origin/$1"
      git reset --hard HEAD
      git clean -d --force
    fi
  )
}

./check-for-repos

for d in *; do
  if [[ ! -d "$d" ]]; then
    continue
  fi

  case "$d" in
    *.github.io)
      switch_to_branch "master"
      ./build-site -r "$d"
    ;;
    *)
      switch_to_branch "gh-pages"
      ./build-site "$d"
    ;;
  esac
done

